### ISSUE TITLE
varnish 4.0 support?

### ISSUE THREAD

**Issue by zstyblik** [xcir/vsltrans#5]
Hello,

I wonder whether varnish 4.0 support is planned. I've spent some time digging around this and, well, varnish 4.0 is just completely different.
Also, it seems that varnish40 branch is just the same as master and varnish30 branches. May be you came to the same conclusion as I did?

Thanks.

**Comment by zstyblik** [comment]
As a matter of fact, most likely only (library) API has changed and the way how to attach to shared memory. May be some attributes(keys) has changed as well. Therefore, once API is brought up to date, once vsltrans is attached to shared memory again, I believe it will work.  My colleague has confused me a bit with ``everything has changed''.

Anyway, we've ended up with parsing varnishlog's output for now. No manpower to pursue changes in API and how to attach it. It remains to be seen how it's going to cope with traffic.

**Comment by xcir** [comment]
vsltrans(support v4) is currently in development.(60%)
But, My regular work is busy now...
Please wait for 2 or 3 week.

**Comment by zstyblik** [comment]
@xcir, please, I was just correcting myself. vsltrans is FOSS, it comes free of charge and you have no obligation to anyone(in my opinion, my $0.02). Therefore, no apologies required on your side.

I've decided to use `varnishlog` instead, because:
- not enough experience to bring up VarnishAPI myself(=> a lot of time required to do so)
- my employer didn't give me more time
- number of lines is 50% of modified version of `vsltrans`(~ 300 V. 600)

It's probably suboptimal to parse `varnishlog` output from performance perspective. But it works and solution was required ASAP from management. I(we) will re-evaluate `vsltrans` once varnish 4.0 support is available :)

Thank you for all the work so far.

**Comment by xcir** [comment]
https://github.com/xcir/vsltrans/commit/e5f8827b9a188b1925f1c7eb0b39f6e939a135d0

support varnish4.0.x
